{% set name = "construct-typing" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/construct-typing-{{ version }}.tar.gz
  sha256: 3d95395b02c727d53ecdd21ad78d9ece83baa24beb71ed5291b4ae4c5e7d78b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - construct ==2.10.67
    - python >=3.7

test:
  imports:
    - construct_typed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/timrid/construct-typing
  summary: Extension for the python package 'construct' that adds typing features
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kevinheavey
